#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt
cat custom_components/hirschmann_switches/manifest.json | jq -r '.requirements | .[]'  | python3 -m pip install -r /dev/stdin