name: Release

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  releases:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/hirschmann_switches/manifest.json"

      - name: "Create archive"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/hirschmann_switches"
          zip hirschmann_switches.zip -r ./

      - name: "Upload the archive as release"
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/hirschmann_switches/hirschmann_switches.zip